// migrate/packages/vue-rxdb-hasura/src/components/documents/Label.vue
<template lang="pug">
span(v-if="label") {{label}}
span(v-else) &nbsp;
</template>

<script lang="ts">
import { ContentsDocument } from '@platyplus/rxdb-hasura'
import { defineComponent, PropType, toRefs } from 'vue'

import { useDocumentLabel } from '../../composables'

export default defineComponent({
  name: 'DocumentLabel',
  props: {
    document: {
      type: Object as PropType<ContentsDocument>,
      default: null
    }
  },
  setup(props) {
    const { document } = toRefs(props)
    const label = useDocumentLabel(document)
    return { label }
  }
})
</script>

// libs/ui/app/src/documents/label.tsx
import { useDocumentLabel } from '@platyplus/react-rxdb-hasura'
import { DocumentComponent } from './types'

export const DocumentLabel: DocumentComponent = ({
  tableInfo,
  role,
  document
}) => {
  const [label] = useDocumentLabel(tableInfo, role, document)
  if (!document) return null
  return <span>{label}</span>
}
