// libs/data-access/react-rxdb-hasura/src/document/label.tsx
import { useMemo } from 'react'

import { InlineValue } from '@platyplus/layout'
import { computeTemplate, ContentsDocument } from '@platyplus/rxdb-hasura'

import { useFormGet } from '../form'
import { useCollectionTableConfig } from '../collection'

export const useDocumentLabelTemplate = (document: ContentsDocument) =>
  useCollectionTableConfig<string>(document?.collection, 'document_label')

export const useDocumentLabel = (
  document: ContentsDocument
): [string, string, (val: string) => void] => {
  const [template, setTemplate] = useDocumentLabelTemplate(document)
  const form = useFormGet(document)

  const label = useMemo(
    () => form && template && computeTemplate(form, template),
    [form, template]
  )

  return [label, template, setTemplate]
}

export const DocumentLabel: React.FC<{
  document: ContentsDocument
  editable?: boolean
}> = ({ document, editable }) => {
  const [value, template, onChange] = useDocumentLabel(document)
  return (
    <InlineValue
      editable={editable}
      value={template}
      label={value}
      onChange={onChange}
    />
  )
}

// migrate/packages/vue-rxdb-hasura/src/components/documents/Label.vue
<template lang="pug">
span(v-if="label") {{label}}
span(v-else) &nbsp;
</template>

<script lang="ts">
import { ContentsDocument } from '@platyplus/rxdb-hasura'
import { defineComponent, PropType, toRefs } from 'vue'

import { useDocumentLabel } from '../../composables'

export default defineComponent({
  name: 'DocumentLabel',
  props: {
    document: {
      type: Object as PropType<ContentsDocument>,
      default: null
    }
  },
  setup(props) {
    const { document } = toRefs(props)
    const label = useDocumentLabel(document)
    return { label }
  }
})
</script>
